builds:
  - binary: collector
    main: cmd/collector/main.go
    goos:
      #- windows
      #- darwin
      - linux
    goarch:
      - amd64
  - binary: agent
    main: cmd/agent/main.go
    goos:
      #- windows
      #- darwin
      - linux
    goarch:
      - amd64
  - binary: query
    main: cmd/query/main.go
    goos:
      #- windows
      #- darwin
      - linux
    goarch:
      - amd64
  - binary: standalone
    main: cmd/standalone/main.go
    goos:
      - linux
    goarch:
      - amd64
   
  
